### ISSUE TITLE
Can we use omnitone for live streaming?

### ISSUE THREAD

**Issue by afgenovese** [GoogleChrome/omnitone#23]
I want to pair 360 video with ambisonics, and stream live it on the internet (delay is acceptable for stitching and pairing). Can omnitone be a solution for this issue? What are the possibilities for live VR reproduction?

**Comment by hoch** [comment]
That's a good question. Theoretically, [MediaStreamAudioSourceNode](https://webaudio.github.io/web-audio-api/#idl-def-MediaStreamAudioSourceNode) supports the streaming. However, I don't think any browser supports the multichannel streaming more that 2 at the moment. If MediaStreamAudioSourceNode supports up to 4 channels, it will work with Omnitone without any issue.

If you want to have multichannel support, be sure to file a bug toward browsers implementors! For instance, [Chrome bug tracker](https://bugs.chromium.org/p/chromium/issues/entry).

**Comment by hoch** [comment]
FWIW, this is the existing bug entry: 
https://bugs.chromium.org/p/chromium/issues/detail?id=453876

In short, if your streaming set up requires the microphone input from getUserMedia API, it's not going to be possible anytime soon. However, if you want to relay the video streaming from the server (not the web browser) I think it might work through MediaStreamAudioSourceNode.

**Comment by gzalles** [comment]
So essentially we can stream it but the user doesn't have control of what they see, it has to be directed on the server side? Just confirming.

**Comment by hoch** [comment]
Let me clarify my opinion:

1. __FOA stream capturing (browser) > streaming > FOA decoding/rendering (browser + Omnitone)__: this is not possible at the moment because the browser uses `getUserMedia()` to capture the audio and it does not support more than 2 channels on any browser at the moment. This API is managed by WebRTC team, so we have to ask them to enable the multi-channel support. ([Chrome bug entry](https://bugs.chromium.org/p/chromium/issues/detail?id=453876))

2. __FOA stream (streaming server) -> streaming -> FOA decoding/rendering (browser + Omnitone)__: this depends on MediaStreamAudioSourceNode. With the new FOARenderer in 0.2.x, you can create a MediaStreamAudioSourceNode and connect the stream into the FOA renderer directly. I haven't tested this in the real web app, but I think it is possible by looking at the [code](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/webaudio/MediaStreamAudioSourceNode.cpp?l=63).

@gzalles I am not sure what you meant by "user doesn't have control of what they see". If the media is encoded for 360 video + FOA stream, user can definitely control what they hear/see.

**Comment by hoch** [comment]
In short, Omnitone is media-type-agnostic. It simply decodes/rendered the FOA stream (4-channel) to the binaural audio stream no matter where the source comes from.

**Comment by hoch** [comment]
Please re-open the issue if any question/problem remains.

**Comment by topherbuckley** [comment]
@hoch

I had a related question to your comments above. I can open another issue if you feel the need but, 

In your README you have the following example code:

'''javascript
// Set up an audio element to feed the ambisonic source audio feed.
var audioElement = document.createElement('audio');
audioElement.src = 'audio-file-foa-acn.wav';
'''

Does this allow for direct references to video files as well as audio files? If not, then what would be the proper syntax or setup for a video file? Are there any file extensions limitations from omnitone itself or just browsers/platforms?
