### ISSUE TITLE
Consider using BASE64 of HRIR data for synchronous loading

### ISSUE THREAD

**Issue by hoch** [GoogleChrome/omnitone#71]
Currently Omnitone's HRIR loading is asynchronous, mainly because it makes loading/decoding process non-blocking. Using BASE64 data for synchronous loading is reasonable considering the data size is not significantly large, but it's still a blocking process.

cc: @drewbitllama @mrdoob -
Would this be better for [Songbird](https://github.com/google/songbird) or the other Three.js-based WebVR apps? I know Songbird's construction/initialization is not asynchronous, so I knew this could be a problem.

On the other hand, resource loading in many web apps is asynchronous, so perhaps Songbird can implement to support asynchronous initialization. (construction => wait for resource loading => fire event when ready to use)

**Comment by drewbitllama** [comment]
The main point myself and Ricardo were considering was being able to support a single-file library that encapsulates all of the functionality. This would be ideal for portability as well as for offline applications. Given that the HRTFs are only 256x16 32-bit float values, it seems like a fairly small header increase in order to allow direct loading from within the library. This is also in line with how Daydream Audio currently handles HRTFs in their C and Java SDKs.

**Comment by hoch** [comment]
Oh, for the offline functionality. I haven't thought about that case. Omnitone usually requires a 360 video/audio stream from the server. So it assumes you have the active internet connection. :)

That's a perfectly valid use case. I'll find a way to encode HRTF to BASE64 and integrate to Omnitone. How urgent is this?

**Comment by drewbitllama** [comment]
Moderately urgent.

**Comment by hoch** [comment]
Some good news from the initial testing:

- PCM file loading vix XHR (core + PCM data) 
  + FOA: 8.2KB + 4.5KB, Load time ~95ms (9ms to 104ms)
  + TOA: 8.2KB + 18.7KBm Load time ~305ms (7ms to 312ms)
- Unified Base64-encoded HRIR
  + FOA/TOA: 48.9KB, Load time ~43ms

So in overall, this might be a huge win for all of us. For, it's ~200% faster for FOA and ~700% faster for TOA. :) The minified library size has gotten bigger up to ~8x, but 50K isn't so bad.

**Comment by mrdoob** [comment]
These numbers look great to me! 👌
